POST http://localhost:8055/api/users
Accept: application/json
Content-Type: application/json

{
  "first_name": "Iliyas2",
  "last_name": "Akbergen2",
  "email": "iliyasakbergen7@gmail.com"
}

###
GET http://localhost:8055/api/users?per_page=3&sort_by=first_name&sort_direction=asc
Accept: application/json

###

PUT http://localhost:8055/api/users/1
Accept: application/json
Content-Type: application/json

{
  "first_name": "Yanis",
  "last_name": "Kegelbar",
  "email": "iliyasakbergen@gmail.com"
}


###
GET http://localhost:8055/api/users/2
Accept: application/json

###
DELETE http://localhost:8055/api/users/7
Accept: application/json
